server:
  port: 18087 # \u670D\u52A1\u7AEF\u53E3\u53F7
spring:
  cloud:
    nacos:
      discovery: # \u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
        server-addr: localhost:8848 # nacos \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
#    sentinel: # \u9650\u6D41\u914D\u7F6E
#      transport:
#        dashboard: 192.168.0.101:8080 # sentinel \u5BA2\u6237\u7AEF\u5730\u5740
#        port: 8719 # \u670D\u52A1\u4E0E dashboard \u8FDB\u884C\u4EA4\u4E92\u7684\u7AEF\u53E3
#  zipkin: # \u94FE\u8DEF\u8FFD\u8E2A\u914D\u7F6E
#    base-url: http://192.168.0.101:9411 # zipkin \u5730\u5740
#    discovery-client-enabled: false # \u662F\u5426\u76D1\u63A7 zipkin \u672C\u8EAB\u7684\u8BF7\u6C42
#    sender:
#      type: web # \u94FE\u8DEF\u6570\u636E\u4EE5\u4EC0\u4E48\u65B9\u5F0F\u8FD4\u9001\u7ED9 zipkin. web \u4F7F\u7528 http \u7684\u5F62\u5F0F\u53D1\u9001
#  sleuth: # \u91C7\u96C6\u7387\u914D\u7F6E
#    sampler:
#      probability: 1 # 采集率, 默认是 百分之10 生产时使用, 开发应该设置为 1 采集全部请求
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    database: 0 # 切换至默认库 0 库
feign: # feign
  sentinel:
    enabled: true # \u5F00\u542F feign \u7684 sentinel \u529F\u80FD