server:
  port: 18090 # \u670D\u52A1\u7AEF\u53E3\u53F7
spring:
  cloud:
    nacos:
      discovery: # \u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
        server-addr: 192.168.0.101:8848 # nacos \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
    sentinel: # \u9650\u6D41\u914D\u7F6E
      transport:
        dashboard: 192.168.0.101:8080 # sentinel \u5BA2\u6237\u7AEF\u5730\u5740
        port: 8719 # \u670D\u52A1\u4E0E dashboard \u8FDB\u884C\u4EA4\u4E92\u7684\u7AEF\u53E3
  zipkin: # \u94FE\u8DEF\u8FFD\u8E2A\u914D\u7F6E
    base-url: http://192.168.0.101:9411 # zipkin \u5730\u5740
    discovery-client-enabled: false # \u662F\u5426\u76D1\u63A7 zipkin \u672C\u8EAB\u7684\u8BF7\u6C42
    sender:
      type: web # \u94FE\u8DEF\u6570\u636E\u4EE5\u4EC0\u4E48\u65B9\u5F0F\u8FD4\u9001\u7ED9 zipkin. web \u4F7F\u7528 http \u7684\u5F62\u5F0F\u53D1\u9001
  sleuth: # \u91C7\u96C6\u7387\u914D\u7F6E
    sampler:
      probability: 1 # \u91C7\u96C6\u7387, \u9ED8\u8BA4\u662F \u767E\u5206\u4E4B10 \u751F\u4EA7\u65F6\u4F7F\u7528, \u5F00\u53D1\u5E94\u8BE5\u8BBE\u7F6E\u4E3A 1 \u91C7\u96C6\u5168\u90E8\u8BF7\u6C42
  thymeleaf:
    cache: false
  datasource: # MySQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/guli_cart?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai # \u8FDE\u63A5\u534F\u8BAE
    username: root
    password: root
  redis: # Redis
    host: 192.168.0.101
    port: 6379
  rabbitmq:
    host: 192.168.0.101
    port: 5672
    virtual-host: /admin # \u865A\u62DF\u4E3B\u673A
    username: admin
    password: admin
feign: # feign
  sentinel:
    enabled: true # \u5F00\u542F feign \u7684 sentinel \u529F\u80FD
mybatis-plus: # mybatis-plus \u914D\u7F6E
  global-config:
    db-config:
      id-type: auto # id \u7B56\u7565, \u751F\u4EA7\u5E94\u8BE5\u4F7F\u7528\u5206\u5E03\u5F0F id. auto \u6570\u636E\u5E93\u81EA\u589E
logging: # \u67E5\u770B\u6267\u884C SQL
  level: # \u7EA7\u522B
    com.atguigu.gmall.cart: debug # debug \u6A21\u5F0F
jwt:
  cookieName: GMALL-TOKEN
  pubKeyPath: /Users/admin/Documents/project/learn/gmall/gmall-auth/src/main/resources/rsa/rsa.pub
  userKey: user-key
  expire: 864000