server:
  port: 18090 # 服务端口号
spring:
  cloud:
    nacos:
      discovery: # 注册中心配置
        server-addr: 192.168.0.101:8848 # nacos 注册中心地址
    sentinel: # 限流配置
      transport:
        dashboard: 192.168.0.101:8080 # sentinel 客户端地址
        port: 8719 # 服务与 dashboard 进行交互的端口
  zipkin: # 链路追踪配置
    base-url: http://192.168.0.101:9411 # zipkin 地址
    discovery-client-enabled: false # 是否监控 zipkin 本身的请求
    sender:
      type: web # 链路数据以什么方式返送给 zipkin. web 使用 http 的形式发送
  sleuth: # 采集率配置
    sampler:
      probability: 1 # 采集率, 默认是 百分之10 生产时使用, 开发应该设置为 1 采集全部请求
  thymeleaf:
    cache: false
  datasource: # MySQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/guli_cart?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai # 连接协议
    username: root
    password: root
  redis: # Redis
    host: 192.168.0.101
    port: 6379
  rabbitmq:
    host: 192.168.0.101
    port: 5672
    virtual-host: /admin # 虚拟主机
    username: admin
    password: admin
  # Spring Task
  # 使用注意事项
  #   1. 配置线程池控制线程数, 不配置可能导致线程资源耗尽宕机
  #   2. 配置统一异常处理器处理异常, 很多时候 异步任务返回不是 future 对象 是 void 需要配置该类作为载体记录异常方便后续处理
  #   3. 配置关机相关参数 是否等待异步是否完成, 等待时间多少
  task:
    execution:
      thread-name-prefix: gmall-cart- # 线程名前缀
      pool:
        core-size: 100 # 核心线程数
        max-size: 500 # 最大可扩展线程数
        queue-capacity: 2000 # 阻塞队列大小
        keep-alive: 60s # 生存时间 带单位
        # 是否允许核心线程数超时, juc 中核心线程数是不能超时的 只有扩展核心数是可以超时的.
        # spring 中默认这个线程池的核心线程数也可以超时. 如果 最大可扩展线程数 空闲时间超过 60s 就可以被销毁. 核心线程数 juc 中是不能被销毁的 最少也要保证 设置的核心线程存活
        # spring 中默认是为 ture 表示 核心线程数也可以被销毁.
        allow-core-thread-timeout: false # 不允许销毁, 避免空闲时间 热点数据收到大量请求 没有线程的尴尬情况发生
      shutdown:
        await-termination: true # 关机时是否需要等待异步任务执行完. 设置为 true, 异步任务没有执行完就关机 在启动也不会在执行 可能导致数据不一致
        await-termination-period: 60s # 关机等待异步任务执行时间
feign: # feign
  sentinel:
    enabled: true # 开启 feign 的 sentinel 功能
mybatis-plus: # mybatis-plus 配置
  global-config:
    db-config:
      id-type: auto # id 策略, 生产应该使用分布式 id. auto 数据库自增
logging: # 查看执行 SQL
  level: # 级别
    com.atguigu.gmall.cart: debug # debug 模式
jwt:
  cookieName: GMALL-TOKEN
  pubKeyPath: /Users/admin/Documents/project/learn/gmall/gmall-auth/src/main/resources/rsa/rsa.pub
  userKey: user-key
  expire: 864000