server:
  port: 18093 # \u670D\u52A1\u7AEF\u53E3\u53F7
  error: # \u5F00\u542F\u5F02\u5E38\u4FE1\u606F\u76F8\u5E94\u7ED9\u524D\u6BB5
    include-exception: true
    include-message: always
spring:
  cloud:
    nacos:
      discovery: # \u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
        server-addr: 192.168.0.101:8848 # nacos \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
    sentinel: # \u9650\u6D41\u914D\u7F6E
      transport:
        dashboard: 192.168.0.101:8080 # sentinel \u5BA2\u6237\u7AEF\u5730\u5740
        port: 8719 # \u670D\u52A1\u4E0E dashboard \u8FDB\u884C\u4EA4\u4E92\u7684\u7AEF\u53E3
  zipkin: # \u94FE\u8DEF\u8FFD\u8E2A\u914D\u7F6E
    base-url: http://192.168.0.101:9411 # zipkin \u5730\u5740
    discovery-client-enabled: false # \u662F\u5426\u76D1\u63A7 zipkin \u672C\u8EAB\u7684\u8BF7\u6C42
    sender:
      type: web # \u94FE\u8DEF\u6570\u636E\u4EE5\u4EC0\u4E48\u65B9\u5F0F\u8FD4\u9001\u7ED9 zipkin. web \u4F7F\u7528 http \u7684\u5F62\u5F0F\u53D1\u9001
  sleuth: # \u91C7\u96C6\u7387\u914D\u7F6E
    sampler:
      probability: 1 # \u91C7\u96C6\u7387, \u9ED8\u8BA4\u662F \u767E\u5206\u4E4B10 \u751F\u4EA7\u65F6\u4F7F\u7528, \u5F00\u53D1\u5E94\u8BE5\u8BBE\u7F6E\u4E3A 1 \u91C7\u96C6\u5168\u90E8\u8BF7\u6C42
  thymeleaf:
    cache: false
  redis: # Redis
    host: 192.168.0.101
  datasource: # MySQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/guli_payment?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai # \u8FDE\u63A5\u534F\u8BAE
    username: root
    password: root
  rabbitmq:
    host: 192.168.0.101
    port: 5672
    virtual-host: /admin # \u865A\u62DF\u4E3B\u673A
    username: admin
    password: admin
    # \u751F\u4EA7\u8005\u786E\u8BA4\u7C7B\u578B
    #   none - \u4E0D\u786E\u8BA4\u6A21\u5F0F
    #   simple - \u540C\u6B65\u963B\u585E\u65B9\u5F0F\u786E\u8BA4, \u6027\u80FD\u4E0D\u9AD8(\u7B49\u5230\u6B7B\u4E3A\u6B62, \u5E76\u53D1\u4E0D\u8FC7\u767E\u53EF\u4EE5\u4F7F\u7528. \u53EF\u9760\u6027\u8F83\u9AD8)
    #   correlated - \u5F02\u6B65\u975E\u963B\u585E\u65B9\u5F0F\u786E\u8BA4, \u6027\u80FD\u8F83\u9AD8
    publisher-confirm-type: correlated
    # \u786E\u8BA4\u6D88\u606F\u662F\u5426\u5230\u8FBE\u961F\u5217
    publisher-returns: true
feign: # feign
  sentinel:
    enabled: true # \u5F00\u542F feign \u7684 sentinel \u529F\u80FD
mybatis-plus: # mybatis-plus \u914D\u7F6E
  global-config:
    db-config:
      id-type: auto # id \u7B56\u7565, \u751F\u4EA7\u5E94\u8BE5\u4F7F\u7528\u5206\u5E03\u5F0F id. auto \u6570\u636E\u5E93\u81EA\u589E
logging: # \u67E5\u770B\u6267\u884C SQL
  level: # \u7EA7\u522B
    com.atguigu.gmall.payment: debug # debug \u6A21\u5F0F
alipay:
  app_id: 2021001163617452
  gatewayUrl: https://openapi.alipay.com/gateway.do
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8Z7EZmanxyFGsK4LrIUeKKrrGxWAHIgPmUV8TtZDs+jeplJSw1ckSY63QhEU444D5qd6xruJHBuB33HG+ik4n8N8nRWi3AtMgpC061oq2DcgtIKMmQHO7/poYDwbpDZrOWXIyiNshFfUOSTUpnrS8UvEks6n6xR/G72r2FG07oZzO7g3XsPMr73wpYajMYC/bhTm6CJGEWZikONNDFkQpVHa+zgitwsqlBuvBvVwGwOHA9B8aRfokwAMl6BDXKoH8BNnSEMpWSTRSwbssayXAQWNU7XKDKGozbn4U2dEbl8GCFzikI/T7ybTNm5gs46ZZBGlq/YB4+v4D3t74Vl6nAgMBAAECggEAOidzhehliYkAlLk1huhV0bMQxewEkQ8RzxTM2SORIWS2q7R+FPtYPkHgU92QFFg85lNltsi5dZ0MylKUFXFRYIi8CL4m7V6E1q12fJPeawVkBXHuig8Y6i1TWRvCUUtuvkTjt++AW/0QECHOtBMVzI95eY+vZwVToq8h/+UcNmxKyVt66Qpo4+r+cUvlvGX5mXgQVC5Ftf/MtHA1i+kjtzBITC0xAvmSXKzjN1YhtcS9rXyMHXBiFhXLdmvOXjkn0Okosr2+tmesXfSwDGhH3ZlOdHzit4D602RNl0nTA1dOUWHuCncs1TrWbriax86P/EYvmzMiHWCVTmmNJC0bMQKBgQD0HAXKNsYsdjCQOV4t3SMqOKaul67x/KA20PmMZVfQ2sQkyjyFgWpL8C16Rzf3zI7df+zF5SkvhFY4+LRZVwX5okEFYTzAZ/NYouj1/DABYOPq0E0sY18/xtq7FJ/CIk8qmCqcczqoyaoxoaC1zAt9E4CYE89iEOnO+GhcI3H3LwKBgQDFlQzvbXhWRyRFkeft/a52XLnyj6t9iP7wNGbGCSeoMDrAu3ZgoqacUPWj5MgSFZdT48H9rF4pPixXoe3jfUNsWBUHqD1F2drDz7lpL0PbpSsgy6ei+D4RwTADsuyXwrkvrWrGro+h6pNJFyly3nea/gloDtJTzfhFFwtNfmqyCQKBgBXzMx4UwMscsY82aV6MZO4V+/71CrkdszZaoiXaswPHuB1qxfhnQ6yiYyR8pO62SR5ns120Fnj8WFh1HJpv9cyVp20ZakIO1tXgiDweOh7VnIjvxBC6usTcV6y81QS62w2Ec0hwIBUvVQtzciUGvP25NDX4igxSYwPGWHP4h/XnAoGAcQN2aKTnBgKfPqPcU4ac+drECXggESgBGof+mRu3cT5U/NS9Oz0Nq6+rMVm1DpMHAdbuqRikq1aCqoVWup51qE0hikWy9ndL6GCynvWIDOSGrLWQZ2kyp5kmy5bWOWAJ6Ll6r7Y9NdIk+NOkw614IFFaNAj2STUw4uPxdRvwD3ECgYEArwOZxR3zl/FZfsvVCXfK8/fhuZXMOp6Huwqky4tNpVLvOyihpOJOcIFj6ZJhoVdmiL8p1/1S+Sm/75gx1tpFurKMNcmYZbisEC7Ukx7RQohZhZTqMPgizlVBTu5nR3xkheaJC9odvyjrWQJ569efXo30gkW04aBp7A15VNG5Z/U=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkWs+3gXMosiWG+EbfRyotWB0waqU3t7qMQSBxU0r3JZoND53jvWQfzrGZ8W+obMc+OgwupODDVxhG/DEKVBIptuUQYdvAjCSH98m2hclFcksspuCy9xS7PyflPE47pVzS6vA3Slvw5OFQ2qUcku4paWnBxguLUGPjEncij5NcyFyk+/k57MmrVJwCZaI+lFOS3Eq2IXc07tWXO4s/2SWr3EJiwJutOGBdA1ddvv1Urrl0pWpEFg30pJB6J7YteuxdEL90kuO5ed/vnTK5qgQRvEelROkUW44xONk1784v28OJXmGICmNL1+KyM/SFbFOSgJZSV1tEXUzvL/xvzFpLwIDAQAB
  notify_url: http://yiki.tech/pay/success
  return_url: http://yiki.tech/pay/ok