server:
  port: 8888 # 服务端口
spring:
  cloud:
    nacos: # 注册中心配置
      discovery:
        server-addr: 192.168.0.101:8848 # 注册中心地址
    gateway: # 网关
      routes: # 路由
        - id: pms-route # 路由唯一标识, 商品管理路由
          uri: lb://pms-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Path=/pms/** # 什么样的请求到此路由 进而进入路由该服务. pms 开头的请求 都 路由到 pms-service 服务

        - id: ums-route # 路由唯一标识, 用户管理路由
          uri: lb://ums-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Path=/ums/** # 什么样的请求到此路由 进而进入路由该服务. ums 开头的请求 都 路由到 ums-service 服务

        - id: wms-route # 路由唯一标识, 仓库管理路由
          uri: lb://wms-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Path=/wms/** # 什么样的请求到此路由 进而进入路由该服务. wms 开头的请求 都 路由到 wms-service 服务

        - id: oms-route # 路由唯一标识, 订单管理路由
          uri: lb://oms-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Path=/oms/** # 什么样的请求到此路由 进而进入路由该服务. oms 开头的请求 都 路由到 oms-service 服务

        - id: sms-route # 路由唯一标识, 营销管理路由
          uri: lb://sms-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Path=/sms/** # 什么样的请求到此路由 进而进入路由该服务. sms 开头的请求 都 路由到 sms-service 服务

        - id: search-route # 路由唯一标识, 搜索工程路由
          uri: lb://search-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Path=/search # 什么样的请求到此路由 进而进入路由该服务. search 开头的请求 都 路由到 search-service 服务

        - id: index-route # 首页的同步请求路由
          uri: lb://index-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Host=gmall.com, www.gmall.com # 因为首页服务可以没有路径, 再使用 路径 Path 进行路由就不合适了, 应该使用域名进行路由
#            - Path=/index/** # 如果写在一个路由里面, 他们的关系是and关系. 同时满足才可以
          filters:
            - Auth=/xxx,/yyy,/zzz,/nnn,/hhh

        - id: index-route2 # 首页的异步请求路由
          uri: lb://index-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Path=/index/** # 什么样的请求到此路由 进而进入路由该服务. index 开头的请求 都 路由到 index-service 服务

        - id: item-route # 路由唯一标识, 商品详情页工程路由
          uri: lb://item-service # 路由到那里, 路由到服务名对应的服务
          predicates: # 断言
            - Host=item.gmall.com # 域名进行路由

        - id: auth-route # 单点登陆路由
          uri: lb://auth-service # 路由唯一标识, 商品详情页工程路由
          predicates: # 断言
            - Host=sso.gmall.com # 域名进行路由

jwt:
  cookieName: GMALL-TOKEN
  token: token
  pubKeyPath: /Users/admin/Documents/project/learn/gmall/gmall-auth/src/main/resources/rsa/rsa.pub